version: '3'

services:
  db:
    image: mysql
    volumes:
      - ./db_data:/var/lib/mysql
      - ./:/root/migrations
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: db666

